package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/AdmCllbckIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
* martes 22 de febrero de 2022 09:50:34 AM COT
*/

public interface AdmCllbckIntOperations 
{
  void notificar (String nombreCompleto, int id);
} // interface AdmCllbckIntOperations
