package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/credencialDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
* martes 22 de febrero de 2022 09:50:34 AM COT
*/

public final class credencialDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String usuario = null;
  public String clave = null;

  public credencialDTO ()
  {
  } // ctor

  public credencialDTO (String _usuario, String _clave)
  {
    usuario = _usuario;
    clave = _clave;
  } // ctor

} // class credencialDTO
