package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/GestionPersonalIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
* martes 22 de febrero de 2022 09:50:34 AM COT
*/

public interface GestionPersonalIntOperations 
{
  void registrarPersonal (s_gestion_usuarios.sop_corba.personalDTO objPersonal);
  boolean consultarPersonal (int id, s_gestion_usuarios.sop_corba.personalDTOHolder objPersonal);
  int abrirSesion (s_gestion_usuarios.sop_corba.credencialDTO objCredencial);
  void registrarCallback (s_gestion_usuarios.sop_corba.AdmCllbckInt objCllbck);
} // interface GestionPersonalIntOperations
